site_name: Semih Vicir
site_url: https://vicir.dev
nav:
    - Hello: index.md
    - Docs:
      - CAMBOT: cambot.md
      - Playstore Reviews: playstore.md
      - BAUROV: baurov.md
      - Navida: navida.md
      - Linux Rescue Notes: linux.md
    - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/C4MCI
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/C4MCI
    - icon: material/web
      link: https://semihvicir.live/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/semihvicir/

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.footer
    - navigation.expand
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    logo: fontawesome/solid/house
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode



markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite:
      guess_lang: false
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences